require("asbjorn.core.keymaps")
require("asbjorn.core.colorscheme")
require("asbjorn.core.options")
require("asbjorn.lazy")
require("asbjorn.nvim-tree")
require("asbjorn.lualine")
require("asbjorn.telescope")
require("asbjorn.nvim-cmp")
require("asbjorn.lsp.mason")
require("asbjorn.lsp.lspconfig")
require("asbjorn.lsp.null-ls")
require("asbjorn.autopairs")
require("asbjorn.treesitter")
require("asbjorn.gitsigns")
vim.g.python3_host_prog = "~/.venvs/nvim/bin/python3"
